target_repo: ghcr.io/bradfordwagner/devtainer
flavor: ansible_playbook
builds:
    - os: archlinux_latest
      archs:
        - linux/amd64
upstream:
    repo: ghcr.io/bradfordwagner/ansible
    tag: 6.1.1
