# created by init task for use with github actons
target_repo: ghcr.io/bradfordwagner/devtainer
upstream:
  repo: ghcr.io/bradfordwagner/ansible
  tag: 5.5.0
builds:
  - os: archlinux_latest
    platforms: [linux/amd64]
