---
- hosts: localhost
  vars:
    user:
      # in some cases we need to create the user
      # so current user would not suffice
      name: bwagner
      create: true
    devtainer:
      dir: '{{ ansible_env.HOME }}/.dotfiles'
      clone:
        strategy: https
        https: https://github.com/bradfordwagner/devtainer.git
        ssh: git@github.com:bradfordwagner/devtainer.git
    # ansible_facts.distribution == "MacOSX"
  tasks:
    # - name: packages - arch
    #   include_tasks: tasks/packages-arch.yml
    #   when: ansible_facts.distribution == "Archlinux"
    # - name: shell
    #   include_tasks: tasks/shell.yml
    - name: link shell
      include_tasks: tasks/link-shell.yml

