---
- hosts: localhost
  vars:
    user:
      name: bwagner
      create: true
  tasks:
    - name: packages - arch
      include_tasks: tasks/packages-arch.yml
      when: ansible_facts.distribution == "Archlinux"
    - name: shell
      include_tasks: tasks/shell.yml

