---
- hosts: localhost
  vars:
    install_vim_shell_packages: true
    brew_install: true
    git_clone: false
    user:
      # in some cases we need to create the user
      # so current user would not suffice
      name: bwagner
      # no password
      password: '!'
      create: '{{ ansible_facts.distribution == "Archlinux" }}'
    devtainer:
      dir: '{{ ansible_env.HOME }}/.dotfiles'
      clone:
        strategy: https
        https: https://github.com/bradfordwagner/devtainer.git
        ssh: git@github.com:bradfordwagner/devtainer.git
    # ansible_facts.distribution == "MacOSX"
  tasks:
    - name: packages - arch
      include_tasks: tasks/packages-arch.yml
      when: ansible_facts.distribution == "Archlinux"

    - name: packages - osx
      include_tasks: tasks/packages-osx.yml
      when: ansible_facts.distribution == "MacOSX" and brew_install

    # mostly user space installation
    - name: create user - {{ user.name }}
      include_tasks: tasks/install-user.yml
      when: user.create
    - name: install dotfiles - this repo!
      include_tasks: tasks/install-dotfiles.yml

    # setup login/etc
    - name: jinga templates
      include_tasks: tasks/jinga-templates.yml
    - name: link shell
      include_tasks: tasks/link-shell.yml

    # link is required first to setup init.vim
    - name: install shell packages [vim,tmux,jumpdir] for {{ user.name }}
      include_tasks: tasks/install-shell-packages.yml
      when: install_vim_shell_packages

    # mac configs
    - name: mac [dock-speed,fzf,screenshots-dir]
      include_tasks: tasks/mac-specific.yml
      when: ansible_facts.distribution == "MacOSX"

    # git clone blocks
    - name: git clone modules
      include_tasks: "{{ task.task }}"
      when: git_clone
      loop_control:
        loop_var: task
      loop:
        - name: bradfordwagner
          task: tasks/git-modules-bradfordwagner.yml
        - name: github
          task: tasks/git-modules-github.yml
