---
- hosts: localhost
  vars:
    user:
      name: bwagner
      create: true
  roles:
    # - role: andrewrothstein.jq
  tasks:
    - name: packages - arch
      include_tasks: tasks/packages-arch.yml
    - name: shell
      include_tasks: tasks/shell.yml

