---
- src: luizgavalda.aur
  version: v0.43
- src: gantsign.oh-my-zsh
  version: 2.2.2
- src: bradfordwagner.jumpdir
  version: 0.5.0

# - src: geerlingguy.homebrew
#   version: 3.1.0
# - src: andrewrothstein.sudoers
#   version: v1.0.9
# - src: andrewrothstein.kubectl
#   version: v1.1.71
# - src: andrewrothstein.hashi
#   version: v0.3.7
# - src: andrewrothstein.terragrunt
#   version: v1.0.74
# - src: elliotweiser.osx-command-line-tools
#   version: 2.3.0
# - src: bradfordwagner.gitops_toolkit
#   version: 0.1.1
