---
version: '3'
env:
  install_packages: false
  git_clone: false
tasks:
  galaxy:
    cmds:
      - ansible-galaxy collection install geerlingguy.mac
      - ansible-galaxy install -r requirements.yml
  playbook:
    internal: true
    vars:
      playbook: '{{ .playbook | default "playbook.yml" }}'
      location: '{{ .location }}'
    deps:
      - galaxy
    cmds:
      - |
        ansible-playbook \
          -i localhost, -c local \
          {{ .playbook | quote }} \
          -e '{install_packages: {{ .install_packages }}}' \
          -e '{git_clone: {{ .git_clone }}}'
  default:
    cmds:
      - task: playbook
        vars:
          install_packages: true
          git_clone: true
  install_packages:
    cmds:
      - task: playbook
        vars:
          install_packages: true
  git:
    cmds:
      - task: playbook
        vars:
          git_clone: true
