---
version: '3'
env:
  install_vim_shell_packages: false
  brew_install: false
  git_clone: false
tasks:
  galaxy:
    cmds:
      - ansible-galaxy collection install geerlingguy.mac
      - ansible-galaxy install -r requirements.yml
  playbook:
    internal: true
    vars:
      playbook: '{{ .playbook | default "playbook.yml" }}'
      location: '{{ .location }}'
    deps:
      - galaxy
    cmds:
      - |
        ansible-playbook \
          -i localhost, -c local \
          {{ .playbook | quote }} \
          -e '{install_vim_shell_packages: {{ .install_vim_shell_packages }}}' \
          -e '{brew_install: {{ .brew_install }}}' \
          -e '{git_clone: {{ .git_clone }}}'
  sudoer:
    cmds:
      - |
        ansible-playbook \
          -i localhost, -c local \
          --ask-become-pass \
          ./pb-sudoer.yml
  default:
    cmds:
      - task: playbook
        vars:
          brew_install: true
          git_clone: true
          install_vim_shell_packages: true
  bare_bones:
    cmds:
      - task: playbook
  install_vim_shell_packages:
    cmds:
      - task: playbook
        vars:
          install_vim_shell_packages: true
  brew_install:
    cmds:
      - task: playbook
        vars:
          brew_install: true
  git:
    cmds:
      - task: playbook
        vars:
          git_clone: true
