---

- vars:
    workspace_dir: '{{ ansible_env.HOME }}/workspace'

    github_dir: '{{ workspace_dir }}/github'

    personal_dir: '{{ github_dir }}/bradfordwagner'
    src_dir: '{{ personal_dir }}/src'
    containers_dir: '{{ personal_dir }}/containers'
    terraform_dir: '{{ personal_dir }}/terraform'
    charts_dir: '{{ personal_dir }}/charts'
    deploy_dir: '{{ personal_dir }}/deploy'
    ansible_roles_dir: '{{ personal_dir }}/ansible_roles'
    go_lib: '{{ personal_dir }}/go.lib'
    go_bin: '{{ personal_dir }}/go.bin'
    forks_dir: '{{ personal_dir }}/forks'
    research_dir: '{{ personal_dir }}/research'
    yaml_dir: '{{ personal_dir }}/yaml'
    ansible_playbooks_dir: '{{ personal_dir }}/ansible_playbooks'

    templates_dir: '{{ personal_dir }}/gh_templates'

    # async control
    # for async: 45/0
    # for sync: 0/5
    async_timeout: 0
    poll_timeout: 5
  block:
   - name: make workspace dirs
     file:
       path: '{{ item }}'
       state: directory
       mode: 0755
     loop:
     - '{{ personal_dir }}'
     - '{{ src_dir }}'
     - '{{ containers_dir }}'
     - '{{ charts_dir }}'
     - '{{ terraform_dir }}'
     - '{{ deploy_dir }}'
     - '{{ templates_dir }}'
     - '{{ go_lib }}'
     - '{{ go_bin }}'
     - '{{ ansible_playbooks_dir }}'

   - name: '{{ deploy_dir }}'
     git:
       repo: '{{ item.repo }}'
       dest: '{{ deploy_dir }}/github.bradfordwagner.deploy.{{ item.name }}'
       version: '{{ item.version | default("main") }}'
     async: '{{ async_timeout }}'
     poll: '{{ poll_timeout }}'
     loop:
     - name: argo.workflow
       repo: https://github.com/bradfordwagner/deploy-argoworkflow.git
     - name: argo.events
       repo: https://github.com/bradfordwagner/deploy-argoevents.git
     - name: argo.events.bus
       repo: https://github.com/bradfordwagner/deploy-argoevents-bus.git
     - name: argo.cd
       repo: https://github.com/bradfordwagner/deploy-argocd.git
     - name: chart.vault
       repo: https://github.com/bradfordwagner/deploy-chart-vault.git
     - name: chart.secrets.store.csi.driver
       repo: https://github.com/bradfordwagner/deploy-secrets-store-csi-driver.git

   - name: '{{ personal_dir }}'
     git:
       repo: '{{ item.repo }}'
       dest: '{{ personal_dir }}/github.bradfordwagner.{{ item.name }}'
       version: '{{ item.version | default("master") }}'
     async: '{{ async_timeout }}'
     poll: '{{ poll_timeout }}'
     loop:
     - name: dotfiles
       repo: https://github.com/bradfordwagner/dotfiles.git

   - name: '{{ src_dir }}'
     git:
       repo: '{{ item.repo }}'
       dest: '{{ src_dir }}/bradfordwagner.src.{{ item.name }}'
       version: '{{ item.version | default("master") }}'
     async: '{{ async_timeout }}'
     poll: '{{ poll_timeout }}'
     loop:
     - name: cheatsheet
       repo: https://github.com/bradfordwagner/cheatsheet.git
     - name: java.firecode
       repo: https://github.com/bradfordwagner/fire-code.git
     - name: grpc
       repo: https://github.com/bradfordwagner/grpc.git
       version: feature/init
     - name: pecan
       repo: https://github.com/bradfordwagner/pecan.git
       version: feature/yabai
     - name: algo.expert
       repo: https://github.com/bradfordwagner/algo-expert.git
       version: main
     - name: docker.cdktf
       repo: https://github.com/bradfordwagner/docker-cdktf.git
     - name: aws.cdktf
       repo: https://github.com/bradfordwagner/aws-cdktf.git
       version: main
     - name: aws.testbed
       repo: https://github.com/bradfordwagner/aws-testbed.git
       version: main
     - name: script.testbed
       repo: https://github.com/bradfordwagner/script-testbed.git
       version: main
     - name: go.testbed
       repo: https://github.com/bradfordwagner/go-testbed.git
       version: main
     - name: amethyst.fork
       repo: https://github.com/bradfordwagner/Amethyst.git
       version: development
     - name: taskfiles
       repo: https://github.com/bradfordwagner/taskfiles.git
       version: main
     - name: gh.actions.testbed
       repo: https://github.com/bradfordwagner/gh-actions-testbed.git
       version: main
     - name: kmonad
       repo: https://github.com/bradfordwagner/container-kmonad.git
       version: main
     - name: tmux.buoyshell
       repo: https://github.com/bradfordwagner/tmux-buoyshell.git
       version: main
     - name: zmk.config.corne
       repo: https://github.com/bradfordwagner/zmk-config-corne.git
       version: main

   # also uses go releaser just like the go.bins
   - name: '{{ go_lib }}'
     git:
       repo: '{{ item.repo }}'
       dest: '{{ go_lib }}/bradfordwagner.go.lib.{{ item.name }}'
     async: '{{ async_timeout }}'
     poll: '{{ poll_timeout }}'
     loop:
     - name: util
       repo: https://github.com/bradfordwagner/go-util.git
     - name: threadpool
       repo: https://github.com/bradfordwagner/go-threadpool.git
     - name: dagger.modules
       repo: https://github.com/bradfordwagner/dagger-modules.git
     - name: dagger.container.builds
       repo: https://github.com/bradfordwagner/dagger-container-builds
     - name: kubeclient
       repo: https://github.com/bradfordwagner/go-kubeclient.git
     - name: sli.job
       repo: https://github.com/bradfordwagner/go-sli-job.git

   - name: '{{ go_bin }}'
     git:
       repo: '{{ item.repo }}'
       dest: '{{ go_bin }}/bradfordwagner.go.bin.{{ item.name }}'
     async: '{{ async_timeout }}'
     poll: '{{ poll_timeout }}'
     loop:
     - name: azure.blob.cli
       repo: https://github.com/bradfordwagner/go-azure-blob-cli.git
     - name: k8s.ks.cli
       repo: https://github.com/bradfordwagner/ks.git
     - name: jumpdir.cli
       repo: https://github.com/bradfordwagner/go-cli-jumpdir.git
     - name: buildkit.ch.cli
       repo: https://github.com/bradfordwagner/go-cli-buildkit-ch.git

   - name: '{{ charts_dir }}'
     git:
       repo: '{{ item.repo }}'
       dest: '{{ charts_dir }}/bradfordwagner.chart.{{ item.name }}'
     async: '{{ async_timeout }}'
     poll: '{{ poll_timeout }}'
     loop:
     - name: argocd.workflows
       repo: https://github.com/bradfordwagner/chart-argo-workflows.git
     - name: argo.events.webhook
       repo: https://github.com/bradfordwagner/argo-events-webhook.git
     - name: argocd.init.contexts
       repo: https://github.com/bradfordwagner/chart-argocd-init-contexts.git
     - name: namespaces
       repo: https://github.com/bradfordwagner/chart-namespaces
     - name: vault.k8s.auth
       repo: https://github.com/bradfordwagner/chart-vault-k8s-auth.git
     - name: docker.buildkit
       repo: https://github.com/bradfordwagner/chart-docker-buildkit.git
     - name: vault.kubernetes.sa
       repo: https://github.com/bradfordwagner/chart-vault-kubernetes-sa.git

   - name: '{{ terraform_dir }}'
     git:
       repo: '{{ item.repo }}'
       dest: '{{ terraform_dir }}/bradfordwagner.tf.{{ item.name }}'
     async: '{{ async_timeout }}'
     poll: '{{ poll_timeout }}'
     loop:
     # build - k8s cluster
     - name: az.infra
       repo: https://github.com/bradfordwagner/tf-az-infra.git
     - name: vault.infra
       repo: https://github.com/bradfordwagner/tf-vault-infra.git
     - name: vault.policy
       repo: https://github.com/bradfordwagner/tf-vault-policy.git
     - name: ci.cd
       repo: https://github.com/bradfordwagner/tf-cicd.git
     - name: testbed
       repo: https://github.com/bradfordwagner/tf-testbed.git
     - name: dry.environments
       repo: https://github.com/bradfordwagner/tf-dry-environments.git
     - name: ws.k8s.infra
       repo: https://github.com/bradfordwagner/tf-ws-k8s-infra.git
     - name: m.k8s.kind
       repo: https://github.com/bradfordwagner/tf-m-k8s-kind.git
     - name: m.vault.helm
       repo: https://github.com/bradfordwagner/tf-m-vault-helm.git
     - name: m.az.acr
       repo: https://github.com/bradfordwagner/tf-m-az-acr.git
     - name: ws.az.acr
       repo: https://github.com/bradfordwagner/tf-ws-az-acr.git

   - name: '{{ ansible_roles_dir }}'
     git:
       repo: '{{ item.repo }}'
       dest: '{{ ansible_roles_dir }}/bradfordwagner.ansible.role.{{ item.name }}'
     async: '{{ async_timeout }}'
     poll: '{{ poll_timeout }}'
     loop:
     - name: azure.blob.cli
       repo: https://github.com/bradfordwagner/ansible-role-azure-blob-cli.git
     - name: gitops.toolkit
       repo: https://github.com/bradfordwagner/ansible-role-gitops-toolkit.git
     - name: jumpdir
       repo: https://github.com/bradfordwagner/ansible-role-jumpdir.git
     - name: docker.buildkit
       repo: https://github.com/bradfordwagner/ansible-role-docker-buildkit.git
     - name: go.releaser.install
       repo: https://github.com/bradfordwagner/ansible-role-go-releaser-install
     - name: github.runner
       repo: https://github.com/bradfordwagner/ansible-role-github-runner.git

   - name: '{{ containers_dir }}'
     git:
       repo: '{{ item.repo }}'
       dest: '{{ containers_dir }}/{{ item.base }}/bradfordwagner.container.{{ item.base }}.{{ item.name }}'
     async: '{{ async_timeout }}'
     poll: '{{ poll_timeout }}'
     loop:
     # containers
     # mirrors
     - name: base
       base: mirrors
       repo: https://github.com/bradfordwagner/container-base.git
     - name: kaniko
       base: mirrors
       repo: https://github.com/bradfordwagner/container-kaniko.git
     - name: argo
       base: mirrors
       repo: https://github.com/bradfordwagner/container-argo.git
     - name: manifest-tool
       base: mirrors
       repo: https://github.com/bradfordwagner/container-manifest-tool.git
     - name: vault
       base: mirrors
       repo: https://github.com/bradfordwagner/container-vault.git
     - name: redis
       base: mirrors
       repo: https://github.com/bradfordwagner/container-redis.git
     - name: helm
       base: mirrors
       repo: https://github.com/bradfordwagner/container-helm.git

     # custom builds
     - name: ansible
       base: custom
       repo: https://github.com/bradfordwagner/container-ansible.git
     - name: store.csi.driver
       base: custom
       repo: https://github.com/bradfordwagner/container-secrets-store-csi-driver.git

     # ansible builds
     - name: go.builder
       base: ansible
       repo: https://github.com/bradfordwagner/container-go-builder.git
     - name: terraform
       base: ansible
       repo: https://github.com/bradfordwagner/container-terraform.git
     - name: devtainer
       base: ansible
       repo: https://github.com/bradfordwagner/devtainer.git
     - name: bkch
       base: ansible
       repo: https://github.com/bradfordwagner/container-bkch.git
     - name: vault.k8s.auth
       base: ansible
       repo: https://github.com/bradfordwagner/container-vault-k8s-auth.git
     - name: pack
       base: ansible
       repo: https://github.com/bradfordwagner/container-pack.git

   - name: '{{ templates_dir }}'
     git:
       repo: '{{ item.repo }}'
       dest: '{{ templates_dir }}/bradfordwagner.template.{{ item.name }}'
     async: '{{ async_timeout }}'
     poll: '{{ poll_timeout }}'
     loop:
     - name: go.lib
       repo: https://github.com/bradfordwagner/gh-template-go-lib.git
     - name: go.cli
       repo: https://github.com/bradfordwagner/gh-template-go-cli.git
     - name: container.mirror.image
       repo: https://github.com/bradfordwagner/gh-template-mirror-image.git
     - name: ansible.role
       repo: https://github.com/bradfordwagner/gh-template-ansible-role.git
     - name: ansible.playbook
       repo: https://github.com/bradfordwagner/gh-template-ansible-playbook.git
     - name: tf.module
       repo: https://github.com/bradfordwagner/gh-template-tf-module.git
     - name: tf.workspaces
       repo: https://github.com/bradfordwagner/gh-template-tf-workspaces.git
     - name: helm.chart
       repo: https://github.com/bradfordwagner/gh-template-helm-chart.git

   - name: '{{ research_dir }}'
     git:
       repo: '{{ item.repo }}'
       dest: '{{ research_dir }}/research.{{ item.name }}'
     async: '{{ async_timeout }}'
     poll: '{{ poll_timeout }}'
     loop:
     - name: vault.sharedsecrets
       repo: https://github.com/bradfordwagner/vault.k8s.sharedsecrets.git
     - name: vault.idp
       repo: https://github.com/bradfordwagner/tf-vault-idp-testbed.git
     - name: vault.testbed
       repo: https://github.com/bradfordwagner/tf-vault-testbed.git

   - name: '{{ forks_dir }}'
     git:
       repo: '{{ item.repo }}'
       dest: '{{ forks_dir }}/gh.forks.{{ item.name }}'
     async: '{{ async_timeout }}'
     poll: '{{ poll_timeout }}'
     loop:
     - name: chart.vault
       repo: https://github.com/bradfordwagner/vault-helm.git
     - name: cert.manager.approver.policy
       repo: https://github.com/bradfordwagner/approver-policy.git
     - name: ansible.role.go.dev
       repo: https://github.com/bradfordwagner/ansible-go-dev.git
     - name: ansible.role.go
       repo: https://github.com/bradfordwagner/ansible-go.git
     - name: gitops.toolkit
       repo: https://github.com/bradfordwagner/gitops-toolkit.git
     - name: vault.secrets.operator
       repo: https://github.com/bradfordwagner/vault-secrets-operator.git
     - name: paketo.go.mod.vendor
       repo: https://github.com/bradfordwagner/paketo-go-mod-vendor.git
     - name: envoy.sidecar.helper
       repo: https://github.com/bradfordwagner/envoy-sidecar-helper.git

   # bulds which use yaml lint
   - name: '{{ yaml_dir }}'
     git:
       repo: '{{ item.repo }}'
       dest: '{{ yaml_dir }}/yaml.{{ item.name }}'
     async: '{{ async_timeout }}'
     poll: '{{ poll_timeout }}'
     loop:
     - name: taskfiles
       repo: https://github.com/bradfordwagner/taskfiles.git
     - name: cicd.smoketests
       repo: https://github.com/bradfordwagner/cicd-smoketests.git

   - name: '{{ ansible_playbooks_dir }}'
     git:
       repo: '{{ item.repo }}'
       dest: '{{ ansible_playbooks_dir }}/ansible.playbook.{{ item.name }}'
     async: '{{ async_timeout }}'
     poll: '{{ poll_timeout }}'
     loop:
     - name: github.runners
       repo: https://github.com/bradfordwagner/github-runners.git
     - name: local.k8s
       repo: https://github.com/bradfordwagner/ansible-playbook-local-k8s
