---

- vars:
    workspace_dir: '{{ ansible_env.HOME }}/workspace'

    github_dir: '{{ workspace_dir }}/github'

    github_ansible_dir: '{{ github_dir }}/ansible'
    github_azure_dir: '{{ github_dir }}/azure'
    github_python_dir: '{{ github_dir }}/python'
    github_shell_dir: '{{ github_dir }}/shell'
    github_go_dir: '{{ github_dir }}/go'
    github_helm_dir: '{{ github_dir }}/helm'
    github_terraform_dir: '{{ github_dir }}/terraform'
    github_k8s_dir: '{{ github_dir }}/k8s'
    github_ubersicht_dir: '{{ github_dir }}/ubersicht'

    # async control
    # for async: 45/0
    # for sync: 0/5
    async_timeout: 0
    poll_timeout: 5
  block:
   - name: make workspace dirs
     file:
       path: '{{ item }}'
       state: directory
       mode: 0755
     loop:
     - '{{ github_ansible_dir }}'
     - '{{ github_azure_dir }}'
     - '{{ github_python_dir }}'
     - '{{ github_shell_dir }}'
     - '{{ github_go_dir }}'
     - '{{ github_helm_dir }}'
     - '{{ github_k8s_dir }}'
     - '{{ github_ubersicht_dir }}'

   - name: '{{ github_ubersicht_dir }}'
     git:
       repo: '{{ item.repo }}'
       dest: '{{ github_ubersicht_dir }}/{{ item.name }}'
       version: '{{ item.version | default("master") }}'
     async: '{{ async_timeout }}'
     poll: '{{ poll_timeout }}'
     loop:
     - repo: https://github.com/bradfordwagner/pecan.git
       name: pecan
       version: feature/yabai
     - repo: https://github.com/kknopper/ubersicht-calendar.git
       name: calendar
     - repo: https://github.com/bradfordwagner/ubersicht-cpu-usage.git
       name: ubersicht-cpu-usage

   - name: '{{ github_ansible_dir }}'
     git:
       repo: '{{ item.repo }}'
       dest: '{{ github_ansible_dir }}/github.ansible.{{ item.name }}'
     async: '{{ async_timeout }}'
     poll: '{{ poll_timeout }}'
     loop:
     - name: andrewrothstein.sudoers
       repo: https://github.com/andrewrothstein/ansible-sudoers.git
     - name: andrewrothstein.go
       repo: https://github.com/andrewrothstein/ansible-go.git
     - name: andrewrothstein.go-dev
       repo: https://github.com/andrewrothstein/ansible-go-dev.git
     - name: andrewrothstein.git
       repo: https://github.com/andrewrothstein/ansible-git.git
     - name: bradfordwagner.terraform-helm3
       repo: https://github.com/bradfordwagner/ansible-terraform-helm3.git
     - name: aaronmell.terraform-provider-helm
       repo: https://github.com/aaronmell/terraform-provider-helm.git
     - name: andrewrothstein.kubernetes-helm
       repo: https://github.com/andrewrothstein/ansible-kubernetes-helm.git
     - name: andrewrothstein.openjdk
       repo: https://github.com/andrewrothstein/ansible-openjdk.git
     - name: andrewrothstein.consul_k8s
       repo: https://github.com/andrewrothstein/ansible-consul_k8s.git
     - name: andrewrothstein.protoc
       repo: https://github.com/andrewrothstein/ansible-protoc.git
     - name: andrewrothstein.alpine.glibc.shim
       repo: https://github.com/andrewrothstein/ansible-alpine-glibc-shim.git
     - name: bradfordwagner.maven
       repo: https://github.com/bradfordwagner/ansible-maven.git
     - name: andrewrothstein.maven
       repo: https://github.com/andrewrothstein/ansible-maven.git
     - name: andrewrothstein.trust.ca
       repo: https://github.com/andrewrothstein/ansible-trust-ca.git
     - name: andrewrothstein.kafka
       repo: https://github.com/andrewrothstein/ansible-kafka.git
     - name: andrewrothstein.vault
       repo: https://github.com/andrewrothstein/ansible-vault.git
     - name: andrewrothstein.prometheus.jmx.exporter
       repo: https://github.com/andrewrothstein/ansible-prometheus_jmx_exporter.git
     - name: andrewrothstein.nats.server
       repo: https://github.com/andrewrothstein/ansible-nats_server.git
     - name: andrewrothstein.buf
       repo: https://github.com/andrewrothstein/ansible-buf.git
     - name: andrewrothstein.miniconda
       repo: https://github.com/andrewrothstein/ansible-miniconda.git
     - name: andrewrothstein.azurecli
       repo: https://github.com/andrewrothstein/ansible-azurecli.git
     - name: andrewrothstein.conda.env
       repo: https://github.com/andrewrothstein/ansible-conda-env.git
     - name: bradfordwagner.protoc
       repo: https://github.com/bradfordwagner/ansible-protoc.git
     - name: andrewrothstein.terragrunt
       repo: https://github.com/andrewrothstein/ansible-terragrunt.git
     - name: andrewrothstein.k9s
       repo: https://github.com/andrewrothstein/ansible-k9s.git
     - name: andrewrothstein.kubectl
       repo: https://github.com/andrewrothstein/ansible-kubectl.git
     - name: bradfordwagner.fork.terragrunt
       repo: https://github.com/bradfordwagner/ansible-terragrunt.git

   - name: '{{ github_helm_dir }}'
     git:
       repo: '{{ item.repo }}'
       dest: '{{ github_helm_dir }}/github.helm.{{ item.name }}'
     async: '{{ async_timeout }}'
     poll: '{{ poll_timeout }}'
     loop:
     - name: hashi.consul
       repo: https://github.com/hashicorp/consul-helm.git
     - name: chart.vault.mirror
       repo: https://github.com/hashicorp/vault-helm.git
     - name: chart.secrets.store.csi.driver.mirror
       repo: https://github.com/kubernetes-sigs/secrets-store-csi-driver.git
     - name: chart.csi-provider-azure.mirror
       repo: https://github.com/Azure/secrets-store-csi-driver-provider-azure
     - name: prometheus
       repo: https://github.com/prometheus-community/helm-charts.git
     - name: cert-manager
       repo: https://github.com/cert-manager/cert-manager.git
     - name: cert-manager-approver-policy
       repo: https://github.com/cert-manager/approver-policy.git
     - name: istio
       repo: https://github.com/istio/istio.git
     - name: kafka.lag.exporter
       repo: https://github.com/seglo/kafka-lag-exporter.git
     - name: argo.helm
       repo: https://github.com/argoproj/argo-helm.git
     - name: bitnami
       repo: https://github.com/bitnami/charts.git

   - name: '{{ github_python_dir }}'
     git:
       repo: '{{ item.repo }}'
       dest: '{{ github_python_dir }}/github.python.{{ item.name }}'
     async: '{{ async_timeout }}'
     poll: '{{ poll_timeout }}'
     loop:
     - name: andrewrothstein.dcb
       repo: https://github.com/andrewrothstein/dcb.git
     - name: alacritty.color.export
       repo: https://github.com/egeesin/alacritty-color-export

   - name: '{{ github_go_dir }}'
     git:
       repo: '{{ item.repo }}'
       dest: '{{ github_go_dir }}/github.go.{{ item.name }}'
     async: '{{ async_timeout }}'
     poll: '{{ poll_timeout }}'
     loop:
     - name: nats.server
       repo: https://github.com/nats-io/nats-server.git
     - name: prototool
       repo: https://github.com/uber/prototool.git
     - name: raft.grpc.example
       repo: https://github.com/Jille/raft-grpc-example.git
     - name: argo.cd
       repo: https://github.com/argoproj/argo-cd.git
     - name: kube.switch
       repo: https://github.com/danielfoehrKn/kubeswitch.git
     - name: vault.csi.provider
       repo: https://github.com/hashicorp/vault-csi-provider.git
     - name: vault.k8s.webhook.injector
       repo: https://github.com/hashicorp/vault-k8s.git
     - name: azure.sdk.go
       repo: https://github.com/Azure/azure-sdk-for-go.git

   - name: '{{ github_shell_dir }}'
     git:
       repo: '{{ item.repo }}'
       dest: '{{ github_shell_dir }}/github.shell.{{ item.name }}'
     async: '{{ async_timeout }}'
     poll: '{{ poll_timeout }}'
     loop:
     - name: cli.visualizer
       repo: https://github.com/dpayne/cli-visualizer.git
     - name: xava
       repo: https://github.com/nikp123/xava.git
     - name: cava
       repo: https://github.com/karlstav/cava.git
     - name: lyrics-in-terminal
       repo: https://github.com/Jugran/lyrics-in-terminal.git
     - name: tmuxinator
       repo: https://github.com/tmuxinator/tmuxinator.git
     - name: base2tone.alacritty.theme
       repo: https://github.com/atelierbram/Base2Tone-alacritty.git
     - name: alacritty.theme
       repo: https://github.com/eendroroy/alacritty-theme.git
     - name: alacritty.nord.theme
       repo: https://github.com/arcticicestudio/nord-alacritty.git
     - name: powerline
       repo: https://github.com/powerline/powerline.git
     - name: ncmpcpp
       repo: https://github.com/ncmpcpp/ncmpcpp.git
     - name: tmux.powerline.gruvbox.theme
       repo: https://github.com/PetrusZ/tmux-powerline-gruvbox-colorscheme.git
     - name: watchexec
       repo: https://github.com/watchexec/watchexec.git
     - name: gotbletu.shownotes.dotfiles
       repo: https://github.com/gotbletu/shownotes.git
     - name: jonaburg.picom.compositor
       repo: https://github.com/jonaburg/picom.git
     - name: corkscrew
       repo: https://github.com/bryanpkc/corkscrew.git
     - name: fzf
       repo: https://github.com/junegunn/fzf.git
     - name: kmonad
       repo: https://github.com/kmonad/kmonad.git
     - name: tmux-tav-fzf
       repo: https://github.com/mudox/tav.git
     - name: tmux-2k
       repo: https://github.com/2KAbhishek/tmux2k.git
     - name: amethyst
       repo: https://github.com/ianyh/Amethyst.git
     - name: nvim.telescope
       repo: https://github.com/nvim-telescope/telescope.nvim.git

   - name: '{{ github_terraform_dir }}'
     git:
       repo: '{{ item.repo }}'
       dest: '{{ github_terraform_dir }}/github.terraform.{{ item.name }}'
     async: '{{ async_timeout }}'
     poll: '{{ poll_timeout }}'
     loop:
     - name: terratest
       repo: https://github.com/gruntwork-io/terratest.git

   - name: '{{ github_k8s_dir }}'
     git:
       repo: '{{ item.repo }}'
       dest: '{{ github_k8s_dir }}/github.k8s.{{ item.name }}'
     async: '{{ async_timeout }}'
     poll: '{{ poll_timeout }}'
     loop:
     - name: iperf3
       repo: https://github.com/Pharb/kubernetes-iperf3.git
     - name: lens.ui
       repo: https://github.com/lensapp/lens
     - name: bank.vault
       repo: https://github.com/banzaicloud/bank-vaults.git
     - name: kurun
       repo: https://github.com/banzaicloud/kurun.git
     - name: examples
       repo: https://github.com/kubernetes/examples.git
     - name: minio
       repo: https://github.com/minio/minio.git
     - name: minio.operator
       repo: https://github.com/minio/operator.git
     - name: secrets.store.csi.driver
       repo: https://github.com/kubernetes-sigs/secrets-store-csi-driver.git
     - name: argo.workflows
       repo: https://github.com/argoproj/argo-workflows.git
     - name: rumstead.gitops.toolkit
       repo: https://github.com/rumstead/gitops-toolkit.git
     - name: istio
       repo: https://github.com/istio/istio.git
     - name: kubernetes.replicator
       repo: https://github.com/mittwald/kubernetes-replicator.git
     - name: secrets.store.csi.driver.provider.azure
       repo: https://github.com/Azure/secrets-store-csi-driver-provider-azure.git
     - name: vault.secrets.operator
       repo: https://github.com/hashicorp/vault-secrets-operator.git
     - name: docker.buildkit
       repo: https://github.com/moby/buildkit.git

   - name: '{{ github_azure_dir }}'
     git:
       repo: '{{ item.repo }}'
       dest: '{{ github_azure_dir }}/github.azure.{{ item.name }}'
     async: '{{ async_timeout }}'
     poll: '{{ poll_timeout }}'
     loop:
     - name: ado.devops.pipelines.docs
       repo: https://github.com/MicrosoftDocs/azure-devops-docs.git
