---

- vars:
    workspace_dir: '{{ ansible_env.HOME }}/workspace'

    github_dir: '{{ workspace_dir }}/github'

    github_ansible_dir: '{{ github_dir }}/ansible'
    github_python_dir: '{{ github_dir }}/python'
    github_shell_dir: '{{ github_dir }}/shell'
    github_go_dir: '{{ github_dir }}/go'
    github_helm_dir: '{{ github_dir }}/helm'
    github_terraform_dir: '{{ github_dir }}/terraform'
    github_k8s_dir: '{{ github_dir }}/k8s'
    github_ubersicht_dir: '{{ github_dir }}/ubersicht'

    # async control
    async_timeout: 45
    poll_timeout: 0
  block:
   - name: make workspace dirs
     file:
       path: '{{ item }}'
       state: directory
       mode: 0755
     loop:
     - '{{ github_ansible_dir }}'
     - '{{ github_python_dir }}'
     - '{{ github_shell_dir }}'
     - '{{ github_go_dir }}'
     - '{{ github_helm_dir }}'
     - '{{ github_k8s_dir }}'
     - '{{ github_ubersicht_dir }}'

   - name: '{{ github_ubersicht_dir }}'
     git:
       repo: '{{ item.repo }}'
       dest: '{{ github_ubersicht_dir }}/{{ item.name }}'
       version: '{{ item.version | default("master") }}'
     async: '{{ async_timeout }}'
     poll: '{{ poll_timeout }}'
     loop:
     - repo: git@github.com:bradfordwagner/pecan.git
       name: pecan
       version: feature/yabai
     - repo: git@github.com:kknopper/ubersicht-calendar.git
       name: calendar
     - repo: git@github.com:bradfordwagner/ubersicht-cpu-usage.git
       name: ubersicht-cpu-usage

   - name: '{{ github_ansible_dir }}'
     git:
       repo: '{{ item.repo }}'
       dest: '{{ github_ansible_dir }}/github.ansible.{{ item.name }}'
       version: '{{ item.version | default("master") }}'
     async: '{{ async_timeout }}'
     poll: '{{ poll_timeout }}'
     loop:
     - name: andrewrothstein.sudoers
       repo: git@github.com:andrewrothstein/ansible-sudoers.git
     - name: andrewrothstein.go
       repo: git@github.com:andrewrothstein/ansible-go.git
     - name: andrewrothstein.go-dev
       repo: git@github.com:andrewrothstein/ansible-go-dev.git
     - name: andrewrothstein.git
       repo: git@github.com:andrewrothstein/ansible-git.git
     - name: bradfordwagner.terraform-helm3
       repo: git@github.com:bradfordwagner/ansible-terraform-helm3.git
     - name: aaronmell.terraform-provider-helm
       repo: git@github.com:aaronmell/terraform-provider-helm.git
       version: dev-v3
     - name: andrewrothstein.kubernetes-helm
       repo: git@github.com:andrewrothstein/ansible-kubernetes-helm.git
     - name: andrewrothstein.openjdk
       repo: git@github.com:andrewrothstein/ansible-openjdk.git
     - name: andrewrothstein.consul_k8s
       repo: git@github.com:andrewrothstein/ansible-consul_k8s.git
     - name: andrewrothstein.protoc
       repo: git@github.com:andrewrothstein/ansible-protoc.git
     - name: andrewrothstein.alpine.glibc.shim
       repo: git@github.com:andrewrothstein/ansible-alpine-glibc-shim.git
     - name: bradfordwagner.maven
       repo: git@github.com:bradfordwagner/ansible-maven.git
     - name: andrewrothstein.maven
       repo: git@github.com:andrewrothstein/ansible-maven.git
     - name: andrewrothstein.trust.ca
       repo: git@github.com:andrewrothstein/ansible-trust-ca.git
     - name: andrewrothstein.kafka
       repo: git@github.com:andrewrothstein/ansible-kafka.git
     - name: andrewrothstein.vault
       repo: git@github.com:andrewrothstein/ansible-vault.git
     - name: andrewrothstein.prometheus.jmx.exporter
       repo: git@github.com:andrewrothstein/ansible-prometheus_jmx_exporter.git
     - name: andrewrothstein.nats.server
       repo: git@github.com:andrewrothstein/ansible-nats_server.git
     - name: andrewrothstein.buf
       repo: git@github.com:andrewrothstein/ansible-buf.git
     - name: andrewrothstein.miniconda
       repo: git@github.com:andrewrothstein/ansible-miniconda.git
     - name: andrewrothstein.azurecli
       repo: git@github.com:andrewrothstein/ansible-azurecli.git
     - name: andrewrothstein.conda.env
       repo: git@github.com:andrewrothstein/ansible-conda-env.git
     - name: bradfordwagner.protoc
       repo: git@github.com:bradfordwagner/ansible-protoc.git
       version: feature/wkt
     - name: andrewrothstein.terragrunt
       repo: git@github.com:andrewrothstein/ansible-terragrunt.git
     - name: andrewrothstein.k9s
       repo: git@github.com:andrewrothstein/ansible-k9s.git
     - name: andrewrothstein.kubectl
       repo: git@github.com:andrewrothstein/ansible-kubectl.git

   - name: '{{ github_helm_dir }}'
     git:
       repo: '{{ item.repo }}'
       dest: '{{ github_helm_dir }}/github.helm.{{ item.name }}'
       version: '{{ item.version | default("master") }}'
     async: '{{ async_timeout }}'
     poll: '{{ poll_timeout }}'
     loop:
     - name: hashi.consul
       repo: git@github.com:hashicorp/consul-helm.git
     - name: chart.vault.mirror
       repo: git@github.com:hashicorp/vault-helm.git
       version: v0.19.0
     - name: prometheus
       repo: git@github.com:prometheus-community/helm-charts.git
       version: main
     - name: cert-manager
       repo: git@github.com:cert-manager/cert-manager.git
       version: v1.10.0
     - name: cert-manager-approver-policy
       repo: git@github.com:cert-manager/approver-policy.git
       version: v1.10.0
     - name: istio
       repo: git@github.com:istio/istio.git
       version: 1.16.1
     - name: kafka.lag.exporter
       repo: git@github.com:seglo/kafka-lag-exporter.git
       version: master

   - name: '{{ github_python_dir }}'
     git:
       repo: '{{ item.repo }}'
       dest: '{{ github_python_dir }}/github.python.{{ item.name }}'
       version: '{{ item.version | default("master") }}'
     async: '{{ async_timeout }}'
     poll: '{{ poll_timeout }}'
     loop:
     - name: andrewrothstein.dcb
       repo: git@github.com:andrewrothstein/dcb.git
     - name: alacritty.color.export
       repo: git@github.com:egeesin/alacritty-color-export

   - name: '{{ github_go_dir }}'
     git:
       repo: '{{ item.repo }}'
       dest: '{{ github_go_dir }}/github.go.{{ item.name }}'
       version: '{{ item.version | default("master") }}'
     async: '{{ async_timeout }}'
     poll: '{{ poll_timeout }}'
     loop:
     - name: nats.server
       repo: git@github.com:nats-io/nats-server.git
       version: main
     - name: prototool
       repo: git@github.com:uber/prototool.git
       version: dev
     - name: raft.grpc.example
       repo: git@github.com:Jille/raft-grpc-example.git
     - name: argo.cd
       repo: git@github.com:argoproj/argo-cd.git
     - name: kube.switch
       repo: git@github.com:danielfoehrKn/kubeswitch.git
     - name: vault.csi.provider
       repo: git@github.com:hashicorp/vault-csi-provider.git

   - name: '{{ github_shell_dir }}'
     git:
       repo: '{{ item.repo }}'
       dest: '{{ github_shell_dir }}/github.shell.{{ item.name }}'
       version: '{{ item.version | default("master") }}'
     async: '{{ async_timeout }}'
     poll: '{{ poll_timeout }}'
     loop:
     - name: cli.visualizer
       repo: git@github.com:dpayne/cli-visualizer.git
       version: v1.8
     - name: xava
       repo: git@github.com:nikp123/xava.git
       version: 0.6.2.3
     - name: cava
       repo: git@github.com:karlstav/cava.git
       version: 0.7.2
     - name: lyrics-in-terminal
       repo: git@github.com:Jugran/lyrics-in-terminal.git
       version: main
     - name: tmuxinator
       repo: git@github.com:tmuxinator/tmuxinator.git
       version:  v0.15.0
     - name: base2tone.alacritty.theme
       repo: git@github.com:atelierbram/Base2Tone-alacritty.git
     - name: alacritty.theme
       repo: git@github.com:eendroroy/alacritty-theme.git
     - name: alacritty.nord.theme
       repo: git@github.com:arcticicestudio/nord-alacritty.git
     - name: powerline
       repo: git@github.com:powerline/powerline.git
       version: 2.8.1
     - name: ncmpcpp
       repo: https://github.com/ncmpcpp/ncmpcpp.git
       version: 0.9.2
     - name: tmux.powerline.gruvbox.theme
       repo: git@github.com:PetrusZ/tmux-powerline-gruvbox-colorscheme.git
     - name: watchexec
       repo: git@github.com:watchexec/watchexec.git
       version: 1.14.1
     - name: gotbletu.shownotes.dotfiles
       repo: git@github.com:gotbletu/shownotes.git
       version: master
     - name: jonaburg.picom.compositor
       repo: git@github.com:jonaburg/picom.git
       version: next
     - name: corkscrew
       repo: https://github.com/bryanpkc/corkscrew.git
       version: master
     - name: fzf
       repo: git@github.com:junegunn/fzf.git
       version: master
     - name: kmonad
       repo: git@github.com:kmonad/kmonad.git
       version: master
     - name: tmux-tav-fzf
       repo: git@github.com:mudox/tav.git
       version: main
     - name: tmux-2k
       repo: git@github.com:2KAbhishek/tmux2k.git
       version: main
     - name: amethyst
       repo: git@github.com:ianyh/Amethyst.git
       version: development

   - name: '{{ github_terraform_dir }}'
     git:
       repo: '{{ item.repo }}'
       dest: '{{ github_terraform_dir }}/github.terraform.{{ item.name }}'
       version: '{{ item.version | default("master") }}'
     async: '{{ async_timeout }}'
     poll: '{{ poll_timeout }}'
     loop:
     - name: terratest
       repo: git@github.com:gruntwork-io/terratest.git
       version: v0.28.8

   - name: '{{ github_k8s_dir }}'
     git:
       repo: '{{ item.repo }}'
       dest: '{{ github_k8s_dir }}/github.k8s.{{ item.name }}'
       version: '{{ item.version | default("master") }}'
     async: '{{ async_timeout }}'
     poll: '{{ poll_timeout }}'
     loop:
     - name: iperf3
       repo: git@github.com:Pharb/kubernetes-iperf3.git
     - name: lens.ui
       repo: git@github.com:lensapp/lens
       version: v3.5.3
     - name: bank.vault
       repo: git@github.com:banzaicloud/bank-vaults.git
     - name: kurun
       repo: git@github.com:banzaicloud/kurun.git
     - name: examples
       repo: git@github.com:kubernetes/examples.git
     - name: minio
       repo: git@github.com:minio/minio.git
     - name: minio.operator
       repo: git@github.com:minio/operator.git
     - name: secrets.store.csi.driver
       repo: git@github.com:kubernetes-sigs/secrets-store-csi-driver.git
     - name: argo.workflows
       repo: git@github.com:argoproj/argo-workflows.git
     - name: rumstead.gitops.toolkit
       repo: git@github.com:rumstead/gitops-toolkit.git
     - name: istio
       repo: https://github.com/istio/istio.git
     - name: kubernetes.replicator
       repo: https://github.com/mittwald/kubernetes-replicator.git
     - name: secrets.store.csi.driver.provider.azure
       repo: https://github.com/Azure/secrets-store-csi-driver-provider-azure.git

