---
- name: create user {{ user.name }}
  ansible.builtin.user:
    name: '{{ user.name }}'
    password: '{{ user.password }}'
    shell: /bin/zsh
  when: user.create
- include_role:
    name: gantsign.oh-my-zsh
  vars:
    users:
    - username: '{{ user.name }}'

