---
- name: jumpdir
  become: yes
  become_user: '{{ user.name }}'
  block:
    - gather_facts:
    - include_role:
        name: bradfordwagner.jumpdir
      vars:
        jd_validate_certs: false

- name: setup oh my zsh plugins/themes
  become: yes
  become_user: '{{ user.name }}'
  block:
    - gather_facts:
    - set_fact:
        user_home: '{{ ansible_env.HOME }}'
    - name: ensure directories exist
      file:
        path: '{{ ansible_env.HOME }}/{{ item }}'
        state: directory
      loop:
        - .cache
        - .ssh
        - .tmux/plugins
        - .vim/bundle
        - Library/Application Support/k9s

    - name: setup tpm
      git:
        repo: '{{ item.repo }}'
        dest: '{{ ansible_env.HOME }}/{{ item.dest }}'
      loop:
      - repo: https://github.com/tmux-plugins/tpm
        dest: .tmux/plugins/tpm

    - name: alacritty
      git:
        repo: '{{ item.repo }}'
        dest: '{{ ansible_env.HOME }}/{{ item.dest }}'
      loop:
        - repo: https://github.com/alacritty/alacritty-theme
          dest: .config/alacritty/themes

    - name: misc
      git:
        repo: '{{ item.repo }}'
        dest: '{{ ansible_env.HOME }}/{{ item.dest }}'
      loop:
        - repo: https://github.com/derailed/k9s.git
          dest: .cache/k9s-skins

    - name: post install link
      file:
        path: '{{ ansible_env.HOME }}/{{ item.path }}'
        state: link
        src: '{{ ansible_env.HOME }}/{{ item.src }}'
        force: true
      loop:
      - src: .cache/k9s-skins/skins
        path: Library/Application Support/k9s/skins

    # TODO fix pynvim
    - shell: '{{ item }}'
      name: install vim plugins
      loop:
        - echo todo fix pynvim support for co-pilot
        - echo todo auto install plugins
        # setup pynvim support for co-pilot
        # - python3 -m pip install --user --upgrade pynvim
        # - nvim +silent +PlugInstall +qall
        # - nvim +silent +PluginInstall +qall
        # - nvim +silent +PackerInstall +qall

- name: npm install language servers
  shell: '{{ item }}'
  loop:
    - npm install -g bash-language-server

