---
- name: pacman - upgrade_cache
  community.general.pacman:
    update_cache: true
- name: pacman - install
  retries: 1
  delay: 3
  # retries: 5
  # delay: 3
  community.general.pacman:
    update_cache: false
    name:
    # - community/gping
    # - net-tools
    # - go
    # - extra/snapd         # for teams integration
    # - community/unclutter # auto hide mouse
    # - corkscrew # ssh over https
    # - extra/nitrogen # set background
    - dnsutils
    # - community/xsel
    # - community/rofi
    # - community/brave-browser
    # - python-pip
    # - community/awesome
    - extra/the_silver_searcher
    - extra/fzf
    # - community/exa
    # - community/bat
    # - community/ttf-jetbrains-mono
    - extra/nodejs
    - extra/npm
    - extra/kubectl
    - extra/k9s
    - extra/helm
    # - alacritty
    # - community/yay
    - extra/watchexec
    - extra/tree
    - extra/zsh
    - extra/tmux
    - extra/rsync
    - core/which
    - core/sudo
    - neovim
    - git
    - gcc
    - bash
    # - vim
    state: present
