---
- name: pacman - upgrade_cache
  community.general.pacman:
    update_cache: true
- name: pacman - install
  retries: 1
  delay: 3
  # retries: 5
  # delay: 3
  community.general.pacman:
    update_cache: false
    state: present
    name:
      - bash
      - core/sudo
      - core/which
      - dnsutils
      - extra/bat
      - extra/fzf
      - extra/helm
      - extra/k9s
      - extra/kubectl
      - extra/nodejs
      - extra/npm
      - extra/rsync
      - extra/the_silver_searcher
      - extra/tmux
      - extra/tree
      - extra/watchexec
      - extra/zsh
      - gcc
      - git
      - go-task
      - neovim
