---
- name: install homebrew cli packages
  include_role:
    name: geerlingguy.mac.homebrew
  vars:
    homebrew_prefix: "{{ (ansible_machine == 'arm64') | ternary('/opt/homebrew', '/usr/local') }}"
    homebrew_install_path: "{{ homebrew_prefix }}/Homebrew"
    homebrew_taps:
    - FelixKratz/formulae
    - bufbuild/buf
    - cjbassi/ytop
    - dagger/tap
    homebrew_uninstalled_packages: []
    homebrew_installed_packages:

    - Azure/kubelogin/kubelogin                # kubelogin - for azure aks login
    - argo
    - argocd
    - awscli
    - azure-cli
    - bash-completion                          # bash completions
    - bat
    - borders                                  # window borders - https://github.com/FelixKratz/JankyBorders
    - buildkit
    - container-diff
    - coreutils
    - corkscrew
    - ctags                                    # used in vim: TagbarToggle
    - dagger/tap/dagger
    - dive                                     # inspect docker images
    - dos2unix
    - expect                                   # for unbuffer command - watch
    - findutils
    - fzf
    - gawk
    - gh                                       # github cli
    - git-delta                                # git colorized differ
    - gnu-sed
    - gnu-tar
    - go
    - go-task                                  # task manager - like makefile, but better
    - gradle
    - hashicorp/tap/terraform-ls               # terraform completions in vim using lsp
    - helm@3
    - hidetatz/tap/kubecolor
    - inetutils                                # net utilities
    - istioctl                                 # istio controller
    - jam
    - jq
    - k3d                                      # installs k3d, partners with rancher for https://github.com/rumstead/gitops-toolkit
    - k9s
    - kind
    - krew                                     # kubectl plugin manager
    - kubectx
    - kubernetes-cli
    - lsd                                      # nerdfont/icons `ls`
    - mkcert
    - nemu
    - neovim
    - newsboat
    - node                                     # required for vim-coc
    - nss                                      # required for mkcert - specifically firefox
    - proctools
    - protobuf
    - pstree
    - pyenv
    - qemu
    - reattach-to-user-namespace
    - ripgrep                                  # https://github.com/BurntSushi/ripgrep - used for grep calls following your gitignore
    - rust
    - sonatype-nexus-community/nancy-tap/nancy # install nancy cli for golang cve detection
    - ssh-copy-id
    - starship
    - sysbench
    - terraform
    - terragrunt
    - tflint
    - the_silver_searcher
    - tmux
    - tmuxinator
    - tree
    - txn2/tap/kubefwd                         # used for forwarding remote k8s cluster to local
    - urlview
    - vault
    - virt-manager
    - watch
    - watchexec
    - wget
    - yamllint
    - yq
    - ytop
    - zellij
- include_role:
    name: geerlingguy.mac.homebrew
  vars:
    homebrew_taps:
    - homebrew/cask-fonts
    - nikitabobko/tap
    homebrew_cask_uninstalled_apps:
    # - jd-gui
    # - pandora
    # - sizeup
    # - honer
    # - drawio
    # - virtualbox
    # - ubersicht
    # - eqmac
    # - homebrew/cask-fonts/font-meslo-nerd-font-mono

    # newly added ignores
    - alfred
    - adobe-acrobat-reader
    - font-meslo-lg-nerd-font
    - homebrew/cask-fonts/font-meslo-nerd-font
    - keyman
    - time-out
    - vlc
    homebrew_cask_apps:
    - aerospace
    - alacritty
    - amethyst
    - bartender
    - brave-browser
    - font-fira-code
    - font-iosevka-term-nerd-font
    - font-jetbrains-mono
    - font-jetbrains-mono-nerd-font
    - google-chrome
    - istat-menus
    - iterm2
    - jetbrains-toolbox
    - microsoft-office
    - postman
    - rancher
    - raycast
    - wezterm
