---
- name: install homebrew cli packages
  include_role:
    name: geerlingguy.mac.homebrew
  vars:
    homebrew_prefix: "{{ (ansible_machine == 'arm64') | ternary('/opt/homebrew', '/usr/local') }}"
    homebrew_install_path: "{{ homebrew_prefix }}/Homebrew"
    homebrew_taps:
    - cjbassi/ytop
    - bufbuild/buf
    - mopidy/mopidy
    homebrew_uninstalled_packages:
    - koekeishiya/formulae/yabai

    # newly added ignores
    - Azure/kubelogin/kubelogin                # kubelogin - for azure aks login
    - ack
    - bats-core
    - bufbuild/buf/buf                         # protobuf generator to replace prototool
    - c-bata/kube-prompt/kube-prompt
    - cmatrix
    - cntlm
    - connect
    - consul
    - csvtk                                    # csv conversion utility
    - cvs
    - darksky-weather
    - dnsmasq                                  # allows for dns hack w/ k8s/kind - https://mjpitz.com/blog/2020/10/21/local-ingress-domains-kind/
    - figlet
    - graphviz                                 # visualize dot lang format files (dependency graph) - https://www.graphviz.org/download/
    - haskell-stack                            # used for compiling kmonad
    - hyperkit # not available on apple silicone
    - ipcalc
    - iproute2mac
    - jfrog-cli
    - koekeishiya/formulae/skhd
    - minikube
    - minio                                    # for testing minio gateway
    - minio-mc                                 # mc client for minio - used for s3-esque ops
    - mopidy
    - mopidy-mpd
    - mopidy-spotify
    - ncmpcpp
    - neofetch
    - nmap
    - nss
    - openjdk
    - openshift-cli
    - pandoc
    - pulseaudio
    - ranger                                   # file system explorer
    - spotify-tui
    - spotifyd
    - tty-clock
    homebrew_installed_packages:
    - argo
    - argocd
    - awscli
    - azure-cli
    - bash-completion                          # bash completions
    - bat
    - cmake
    - coreutils
    - corkscrew
    - ctags                                    # used in vim: TagbarToggle
    - danielfoehrkn/switch/switch              # kubectl switch helper - https://github.com/danielfoehrKn/kubeswitch/blob/master/docs/installation.md
    - dive                                     # inspect docker images
    - docker
    - dos2unix
    - expect                                   # for unbuffer command - watch
    - fzf
    - gawk
    - gh                                       # github cli
    - git-delta                                # git colorized differ
    - gnu-sed
    - gnu-tar
    - go-task                                  # task manager - like makefile, but better
    - hashicorp/tap/terraform-ls               # terraform completions in vim using lsp
    - helm@3
    - inetutils                                # net utilities
    - istioctl                                 # istio controller
    - jq
    - k3d                                      # installs k3d, partners with rancher for https://github.com/rumstead/gitops-toolkit
    - k9s
    - kind
    - krew                                     # kubectl plugin manager
    - kubectx
    - kubernetes-cli
    - lsd                                      # nerdfont/icons `ls`
    - macvim
    - mkcert
    - neovim
    - node                                     # required for vim-coc
    - proctools
    - protobuf
    - prototool
    - pstree
    - pyenv
    - python-yq
    - reattach-to-user-namespace
    - rust
    - sonatype-nexus-community/nancy-tap/nancy # install nancy cli for golang cve detection
    - ssh-copy-id
    - terragrunt
    - terraform
    - tflint
    - the_silver_searcher
    - tmux
    - tmuxinator
    - tree
    - txn2/tap/kubefwd                         # used for forwarding remote k8s cluster to local
    - urlview
    - vault
    - watch
    - watchexec
    - wget
    - ytop

- include_role:
    name: geerlingguy.mac.homebrew
  vars:
    homebrew_taps:
    - homebrew/cask-fonts
    homebrew_cask_uninstalled_apps:
    # - jd-gui
    # - pandora
    # - sizeup
    # - bartender
    # - honer
    # - drawio
    # - virtualbox
    # - spotify
    # - ubersicht
    # - eqmac
    # - iterm2
    # - homebrew/cask-fonts/font-meslo-nerd-font-mono

    # newly added ignores
    - adobe-acrobat-reader
    - font-meslo-lg-nerd-font
    - homebrew/cask-fonts/font-meslo-nerd-font
    - keyman
    - time-out
    - vlc
    homebrew_cask_apps:
    - alacritty
    - alfred
    - amethyst
    - brave-browser
    - dozer
    - firefox
    - font-fira-code
    - font-jetbrains-mono
    - font-jetbrains-mono-nerd-font
    - google-chrome
    - istat-menus
    - jetbrains-toolbox
    - microsoft-office
    - postman
    - rancher

