---
- name: install homebrew cli packages
  include_role:
    name: geerlingguy.mac.homebrew
  vars:
    homebrew_prefix: "{{ (ansible_machine == 'arm64') | ternary('/opt/homebrew', '/usr/local') }}"
    homebrew_install_path: "{{ homebrew_prefix }}/Homebrew"
    homebrew_taps:
    - cjbassi/ytop
    - bufbuild/buf
    - mopidy/mopidy
    homebrew_uninstalled_packages: []
    homebrew_installed_packages:
    - Azure/kubelogin/kubelogin                # kubelogin - for azure aks login
    - argo
    - argocd
    - awscli
    - azure-cli
    - bash-completion                          # bash completions
    - bat
    - buildkit
    - cmake
    - container-diff
    - coreutils
    - corkscrew
    - ctags                                    # used in vim: TagbarToggle
    - danielfoehrkn/switch/switch              # kubectl switch helper - https://github.com/danielfoehrKn/kubeswitch/blob/master/docs/installation.md
    - dive                                     # inspect docker images
    - docker
    - dos2unix
    - expect                                   # for unbuffer command - watch
    - findutils
    - fzf
    - gawk
    - gh                                       # github cli
    - git-delta                                # git colorized differ
    - gnu-sed
    - gnu-tar
    - go-task                                  # task manager - like makefile, but better
    - hashicorp/tap/terraform-ls               # terraform completions in vim using lsp
    - helm@3
    - inetutils                                # net utilities
    - istioctl                                 # istio controller
    - jq
    - k3d                                      # installs k3d, partners with rancher for https://github.com/rumstead/gitops-toolkit
    - k9s
    - kind
    - krew                                     # kubectl plugin manager
    - kubectx
    - kubernetes-cli
    - lsd                                      # nerdfont/icons `ls`
    - macvim
    - mkcert
    - mopidy
    - mopidy-mpd
    - mopidy-spotify
    - ncmpcpp
    - neovim
    - node                                     # required for vim-coc
    - nss                                      # required for mkcert - specifically firefox
    - proctools
    - protobuf
    - prototool
    - pstree
    - pulseaudio
    - pyenv
    - python-yq
    - reattach-to-user-namespace
    - ripgrep                                  # https://github.com/BurntSushi/ripgrep - used for grep calls following your gitignore
    - rust
    - sonatype-nexus-community/nancy-tap/nancy # install nancy cli for golang cve detection
    - spotify-tui
    - spotify_player
    - spotifyd
    - ssh-copy-id
    - terraform
    - terragrunt
    - tflint
    - the_silver_searcher
    - tmux
    - tmuxinator
    - tree
    - txn2/tap/kubefwd                         # used for forwarding remote k8s cluster to local
    - urlview
    - vault
    - watch
    - watchexec
    - wget
    - yamllint
    - ytop

- include_role:
    name: geerlingguy.mac.homebrew
  vars:
    homebrew_taps:
    - homebrew/cask-fonts
    homebrew_cask_uninstalled_apps:
    # - jd-gui
    # - pandora
    # - sizeup
    # - bartender
    # - honer
    # - drawio
    # - virtualbox
    # - spotify
    # - ubersicht
    # - eqmac
    # - homebrew/cask-fonts/font-meslo-nerd-font-mono

    # newly added ignores
    - adobe-acrobat-reader
    - font-meslo-lg-nerd-font
    - homebrew/cask-fonts/font-meslo-nerd-font
    - keyman
    - time-out
    - vlc
    homebrew_cask_apps:
    - alacritty
    - alfred
    - amethyst
    - brave-browser
    - dozer
    - firefox
    - font-fira-code
    - font-jetbrains-mono
    - font-jetbrains-mono-nerd-font
    - google-chrome
    - istat-menus
    - iterm2
    - jetbrains-toolbox
    - microsoft-office
    - postman
    - rancher
    - wezterm
