# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

[directory]
disabled = false

[username]
disabled = true

[git_metrics]
disabled = false

[golang]
disabled = true

[helm]
disabled = true
