live_config_reload = true

# https://github.com/alacritty/alacritty-theme/tree/master/themes
import = [
#    "~/.config/alacritty/themes/themes/kanagawa_wave.toml"
    "~/.config/alacritty/themes/themes/tokyo-night.toml"
]


[colors]
draw_bold_text_with_bright_colors = true

[colors.primary]
background = "0x000000"

[font]
size = 12

[font.normal]
#family = "JetBrainsMono Nerd Font Mono"
#style = "Bold"
family = "IosevkaTerm Nerd Font Mono"
style = "ExtraBold"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Command"

[selection]
save_to_clipboard = true

[shell]
args = ["--login"]
program = "zsh"

[window]
blur = true
decorations = "none"
dynamic_padding = false
opacity = 0.75
option_as_alt = "OnlyLeft"

[window.padding]
x = 4
y = 4
