font:
  size: 11
  normal:
    family: JetBrainsMono Nerd Font Mono
    style: Bold

#background_opacity: .90
live_config_reload: true

selection:
  save_to_clipboard: true

shell:
  program: zsh
  args:
  - --login

draw_bold_text_with_bright_colors: true


schemes:
  # Tokyo Night theme, based on both:
  #   https://github.com/ghifarit53/tokyonight-vim
  #   https://github.com/enkia/tokyo-night-vscode-theme
  tokyo-night: &tokyo-night
    # Default colors
    primary:
      background: '0x1a1b26'
      foreground: '0xa9b1d6'

    cursor:
      text:   CellBackground
      cursor: CellForeground
    vi_mode_cursor:
      text:   CellBackground
      cursor: CellForeground

    # Normal colors
    normal:
      black:   '0x32344a'
      red:     '0xf7768e'
      green:   '0x9ece6a'
      yellow:  '0xe0af68'
      blue:    '0x7aa2f7'
      magenta: '0xad8ee6'
      cyan:    '0x449dab'
      white:   '0x787c99'

    # Bright colors
    bright:
      black:   '0x444b6a'
      red:     '0xff7a93'
      green:   '0xb9f27c'
      yellow:  '0xff9e64'
      blue:    '0x7da6ff'
      magenta: '0xbb9af7'
      cyan:    '0x0db9d7'
      white:   '0xacb0d0'

  tokyo-night-storm: &tokyo-night-storm
    # Default colors
    primary:
      background: '0x24283b'
      foreground: '0xa9b1d6'

    cursor:
      text:   CellBackground
      cursor: CellForeground
    vi_mode_cursor:
      text:   CellBackground
      cursor: CellForeground

    # Normal colors
    normal:
      black:   '0x32344a'
      red:     '0xf7768e'
      green:   '0x9ece6a'
      yellow:  '0xe0af68'
      blue:    '0x7aa2f7'
      magenta: '0xad8ee6'
      cyan:    '0x449dab'
      white:   '0x9699a8'

    # Bright colors
    bright:
      black:   '0x444b6a'
      red:     '0xff7a93'
      green:   '0xb9f27c'
      yellow:  '0xff9e64'
      blue:    '0x7da6ff'
      magenta: '0xbb9af7'
      cyan:    '0x0db9d7'
      white:   '0xacb0d0'

  # Catppuccin! - https://github.com/catppuccin/alacritty/blob/main/catppuccin.yml
  catpuccin: &catppuccin
    # Default colors
    primary:
      background: '0x1E1E28'
      foreground: '0xD7DAE0'
    # Colors the cursor will use if `custom_cursor_colors` is true
    cursor:
      text: '0x1E1E28'
      cursor: '0xB3E1A3'
    # Normal colors
    normal:
      black:   '0x6E6C7C'
      red:     '0xE28C8C'
      green:   '0xB3E1A3'
      yellow:  '0xEADDA0'
      blue:    '0xA4B9EF'
      magenta: '0xC6AAE8'
      cyan:    '0xF0AFE1'
      white:   '0xD7DAE0'
    # Bright colors
    bright:
      black:   '0x6E6C7C'
      red:     '0xE28C8C'
      green:   '0xB3E1A3'
      yellow:  '0xEADDA0'
      blue:    '0xA4B9EF'
      magenta: '0xC6AAE8'
      cyan:    '0xF0AFE1'
      white:   '0xD7DAE0'
    indexed_colors:
      - { index: 16, color: '0xECBFBD' }
      - { index: 17, color: '0x3E4058' }

  # Colors (SMYCK)
  smyck: &smyck
    primary:
      background: '0x232423'
      foreground: '0xF8F8F8'
      bright_foreground: '0xfeffff'

    normal:
      black:   '0x000000'
      red:     '0xC75646'
      green:   '0x8EB33B'
      yellow:  '0xD0B03C'
      blue:    '0x4E90A7'
      magenta: '0xC8A0D1'
      cyan:    '0x218693'
      white:   '0xB0B0B0'

    bright:
      black:   '0x5D5D5D'
      red:     '0xE09690'
      green:   '0xCDEE69'
      yellow:  '0xFFE377'
      blue:    '0x9CD9F0'
      magenta: '0xFBB1F9'
      cyan:    '0x77DFD8'
      white:   '0xF7F7F7'

key_bindings:
- { key: N,      mods: Command, action: SpawnNewInstance       }
#- { key: Return, mods: Command, action: ToggleSimpleFullscreen }

window:
  # Values for `decorations` (macOS only):
  #     - transparent: Title bar, transparent background and title bar buttons
  #     - buttonless: Title bar, transparent background, but no title bar buttons
  #     - none: Neither borders nor title bar
  #     - full: Borders and title bar
# decorations: none
  decorations: buttonless
  padding:
    x: 4
    y: 4
  dynamic_padding: false
  option_as_alt: OnlyLeft # allow alt to be used, it was mapping to escape - see: https://github.com/alacritty/alacritty/releases/tag/v0.12.0

colors: *tokyo-night # tokyo-night, tokyo-night-storm, catppuccin, smyck

