[general]
live_config_reload = true
# https://github.com/alacritty/alacritty-theme/tree/master/themes
import = [
#    "~/.config/alacritty/themes/themes/kanagawa_wave.toml"
    "~/.config/alacritty/themes/themes/tokyo-night.toml"
]


[colors]
draw_bold_text_with_bright_colors = true
primary.background = "0x000000"

[font]
size = 18

[font.normal]
# family = "JetBrainsMono Nerd Font Mono"
# style = "Bold"
family = "IosevkaTerm Nerd Font Mono"
style = "ExtraBold"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "N"
mods = "Command"

[selection]
save_to_clipboard = true

[terminal.shell]
args = ["--login"]
program = "zsh"

[window]
blur = true
decorations = "None"
dynamic_padding = false
# opacity = 1.00
opacity = 0.10
option_as_alt = "Both"

[window.padding]
x = 4
y = 4
